TechXpress.Web/Controllers/StockController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace TechXpress.Web.Controllers
{
    [Authorize(Roles = nameof(Roles.Admin))]
    public class StockController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;

        public StockController(IUnitOfWork UnitOfWork)
        {
            _UnitOfWork = UnitOfWork;
        }

        public async Task<IActionResult> Index(string sTerm = "")
        {
            var stocks = await _UnitOfWork.Stock.GetStocks(sTerm);
            return View(stocks);
        }

        public async Task<IActionResult> ManangeStock(int productId)
        {
            var existingStock = await _UnitOfWork.Stock.GetStockByProductId(productId);
            var stock = new StockViewModel
            {
                ProductId = productId,
                Quantity = existingStock != null
            ? existingStock.Quantity : 0
            };
            return View(stock);
        }

        [HttpPost]
        public async Task<IActionResult> ManangeStock(StockViewModel stock)
        {
            if (!ModelState.IsValid)
                return View(stock);
            try
            {
                await _UnitOfWork.Stock.ManageStock(stock);
                TempData["successMessage"] = "Stock is updated successfully.";
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "Something went wrong!!";
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

TechXpress.Web/Views/Stock/Index.cshtml
@model IEnumerable<StockDisplayModel>
@{
    Layout = "_AdminLayout";
}
<h2>Stocks</h2>

<form asp-action="Index" method="get" class="my-2 d-flex gap-2">
    <input type="text" name="sTerm" class="form-control w-25" placeholder="Search by product" />
    <button type="submit" class="btn btn-primary">Find</button>
    <a asp-action="Index" asp-controller="Stock" class="btn btn-primary">Clear</a>
</form>

<table class="table table-bordered">
  <tr>
    <th>Product</th>
    <th>Stock</th>
    <th>Actions</th>
  </tr>
  @foreach(var item in Model)
  {
    <tr>
      <td>@item.ProductName</td>
      <td>@item.Quantity</td>
      <td>
         <a asp-action="ManangeStock" asp-controller="Stock" asp-route-productId="@item.ProductId" class="btn btn-info"> Update Stock</a>
      </td>
    </tr>
  }
</table>

TechXpress.Web/Views/Stock/ManangeStock.cshtml
@model StockViewModel
@{
    Layout = "_AdminLayout";
}

<div style="width:50%">
<h2> Manage Stock </h2>
<a asp-action="Index" asp-controller="Stock" class="btn btn-primary">Back</a>
<form asp-action="ManangeStock">
   <input type="hidden" asp-for="ProductId" />

   <div class="my-2">
      <label>Quantity</label>
      <input type="number" class="form-control" asp-for="Quantity" />
      <span asp-validation-for="Quantity" class="text-danger"></span>
   </div>

   <div class="my-2">
      <button type="submit" class="btn btn-info">Update</button>
   </div>
</form>
</div>